#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# scripts/prod/bootstrap-host.sh
#
# One-time setup for a fresh host (Linux server or Mac for dry-run).
#
# What it does:
#   1. Verifies Docker + Compose are installed (instructs you if not)
#   2. Creates the standard directory layout under $ACA_ROOT (default /opt/aca)
#   3. Clones the custom app repos under $ACA_ROOT/repos if missing
#   4. Generates compose/prod/.env from .env.example with strong random secrets
#   5. Pulls the required Docker images
#
# It does NOT bring the stack up — that's a deliberate separate step so you can
# review the generated .env first.
#
# Usage:
#   sudo mkdir -p /opt/aca && sudo chown $USER:$USER /opt/aca   # one-time
#   cd /opt/aca && git clone https://github.com/kAIzenEd/erp-platform-infra.git infra
#   /opt/aca/infra/scripts/prod/bootstrap-host.sh
#
# Mac dry-run:
#   ACA_ROOT=$HOME/aca-dryrun STACK_NAME=ets_prod_dryrun WEB_PORT=8081 \
#     ~/ets-repos/erp-platform-infra/scripts/prod/bootstrap-host.sh
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

ACA_ROOT="${ACA_ROOT:-/opt/aca}"
ADMISSIONS_REMOTE="${ADMISSIONS_REMOTE:-https://github.com/kAIzenEd/ets_admissions.git}"
STUDENTS_REMOTE="${STUDENTS_REMOTE:-https://github.com/kAIzenEd/ets_students.git}"
INFRA_REMOTE="${INFRA_REMOTE:-https://github.com/kAIzenEd/erp-platform-infra.git}"

# These will land in the generated .env. Override via env to customize.
STACK_NAME="${STACK_NAME:-ets_prod}"
WEB_PORT="${WEB_PORT:-8080}"
BIND_ADDR="${BIND_ADDR:-0.0.0.0}"
SITE_NAME="${SITE_NAME:-erp.aca.local}"
FRAPPE_IMAGE="${FRAPPE_IMAGE:-frappe/erpnext:v16.15.1}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
COMPOSE_DIR="$REPO_ROOT/compose/prod"
ENV_FILE="$COMPOSE_DIR/.env"

log() { printf '\033[1;32m[bootstrap]\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[bootstrap]\033[0m %s\n' "$*"; }
die() { printf '\033[1;31m[bootstrap]\033[0m %s\n' "$*" >&2; exit 1; }

# ── 1. Verify Docker ────────────────────────────────────────────────────────
log "checking Docker"
if ! command -v docker >/dev/null 2>&1; then
  die "Docker is not installed. Install with:
       Ubuntu/Debian: curl -fsSL https://get.docker.com | sudo sh
                      sudo usermod -aG docker \$USER && newgrp docker
       RHEL/Rocky:    sudo dnf install -y docker docker-compose-plugin
                      sudo systemctl enable --now docker
                      sudo usermod -aG docker \$USER && newgrp docker
       macOS:         install Docker Desktop"
fi
if ! docker compose version >/dev/null 2>&1; then
  die "'docker compose' plugin not installed. Install the Compose plugin
       (docker-compose-plugin or docker-buildx-plugin) and retry."
fi
log "  docker:  $(docker --version)"
log "  compose: $(docker compose version | head -1)"

# ── 2. Directory layout ─────────────────────────────────────────────────────
log "ensuring directory layout under $ACA_ROOT"
if [[ ! -d "$ACA_ROOT" ]]; then
  die "$ACA_ROOT does not exist. Create it first:
       sudo mkdir -p $ACA_ROOT && sudo chown \$USER:\$USER $ACA_ROOT"
fi
mkdir -p "$ACA_ROOT"/{repos,backups,infra}

# ── 3. Clone or verify repos ────────────────────────────────────────────────
clone_or_pull() {
  local url="$1" dest="$2" name="$3"
  if [[ -d "$dest/.git" ]]; then
    log "  $name already cloned at $dest (skip)"
  elif [[ -d "$dest" ]]; then
    warn "  $dest exists but is not a git repo — leaving as-is"
  else
    log "  cloning $name into $dest"
    git clone --depth 50 "$url" "$dest"
  fi
}
clone_or_pull "$ADMISSIONS_REMOTE" "$ACA_ROOT/repos/ets_admissions" "ets_admissions"
clone_or_pull "$STUDENTS_REMOTE"   "$ACA_ROOT/repos/ets_students"   "ets_students"

# If the infra clone is somewhere else (e.g., Mac dev path), don't move it.
if [[ "$REPO_ROOT" != "$ACA_ROOT/infra" ]]; then
  warn "this script is running from $REPO_ROOT"
  warn "  if you want infra to live at $ACA_ROOT/infra, clone it there:"
  warn "    git clone $INFRA_REMOTE $ACA_ROOT/infra"
fi

# ── 4. Generate .env if it doesn't exist ────────────────────────────────────
if [[ -f "$ENV_FILE" ]]; then
  warn ".env already exists at $ENV_FILE — leaving it alone"
  warn "  delete it manually if you want bootstrap to regenerate it"
else
  log "generating $ENV_FILE with strong random secrets"
  DB_ROOT_PASSWORD="$(openssl rand -hex 24)"
  ADMIN_PASSWORD="$(openssl rand -hex 32)"
  cat > "$ENV_FILE" <<EOF
# Auto-generated by bootstrap-host.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Keep this file out of git. Rotate DB_ROOT_PASSWORD via dedicated procedure.

STACK_NAME=$STACK_NAME
FRAPPE_IMAGE=$FRAPPE_IMAGE
REPOS_ROOT=$ACA_ROOT/repos
SITE_NAME=$SITE_NAME
DB_ROOT_PASSWORD=$DB_ROOT_PASSWORD
ADMIN_PASSWORD=$ADMIN_PASSWORD
WEB_PORT=$WEB_PORT
BIND_ADDR=$BIND_ADDR
EOF
  chmod 600 "$ENV_FILE"
  log "  wrote $ENV_FILE (mode 600)"
  log "  DB_ROOT_PASSWORD and ADMIN_PASSWORD were generated — save them to your password manager NOW"
fi

# ── 5. Pull images ──────────────────────────────────────────────────────────
log "pulling Docker images"
docker compose --env-file "$ENV_FILE" -f "$COMPOSE_DIR/compose.yml" pull --quiet

# ── 6. Done ─────────────────────────────────────────────────────────────────
log ""
log "──────────────────────────────────────────────────────────────────────"
log "Bootstrap complete. Next steps:"
log ""
log "  1. Review $ENV_FILE — confirm SITE_NAME and passwords"
log "  2. Bring the stack up:"
log "       cd $COMPOSE_DIR"
log "       docker compose --env-file .env up -d"
log "  3. Tail the one-shot bootstrap (only on first up):"
log "       docker compose --env-file .env logs -f create-site"
log "  4. When create-site exits 0, open: http://<host>:${WEB_PORT}"
log "     - Site name (Host header): $SITE_NAME"
log "     - First admin login: Administrator / <ADMIN_PASSWORD from .env>"
log "──────────────────────────────────────────────────────────────────────"
